name = "proxy-panel"
main = "worker/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Serve frontend from dist/
[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "proxy-panel"
database_id = "6c89686c-97cc-4ea5-a053-7e6acd5b9051"
